name: magpie_fly_example
description: Demonstrates how to use the magpie_fly plugin.
publish_to: 'none'
version: 0.0.1
homepage: https://pub.dev/

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: any
  video_player: any
  flutter_markdown: any
  android_intent: any
  flutter_webview_plugin: any
  fluttertoast: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  magpie_fly:
    path: ../

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - doc/
    - doc/resource/
    - lib/demo/
    - lib/demo/horizonal_scroll/
    - lib/demo/draggable_btn/
    - lib/demo/pinned_sliver/
    - lib/demo/pinned_sliver/component/
    - lib/demo/popup_window/
    - lib/demo/search_input/
    - lib/demo/video/
    - lib/demo/video/component/
    - lib/demo/banner_widget/

